### ISSUE TITLE
Cannot find module `sonner/dist/styles.css?url` after upgrading to v2.0.4

### ISSUE THREAD

**Issue by janhesters** [emilkowalski/sonner#648]
**Description**
After upgrading Sonner from v2.0.3 to v2.0.4, the build fails with the following error:

```
Cannot find module 'sonner/dist/styles.css?url'
```

Prior to this release, importing styles worked correctly. It appears that the path or packaging of the CSS file was changed in v2.0.4.

It seems likely that the new release either removed or relocated `dist/styles.css`, but the documentation (and/or code) still expects to import it from `sonner/dist/styles.css?url`.

**To Reproduce**

1. In your project, update `package.json` to use:

   ```json
   "dependencies": {
     "sonner": "2.0.4",
     /* ...other dependencies... */
   }
   ```
2. Run your package manager to install the new version:

   ```bash
   npm install
   # or
   yarn install
   ```
3. In your application code, import the styles exactly as before. For example:

   ```js
   import { Toaster } from "sonner";
   import "sonner/dist/styles.css?url";
   ```

  or
  
  ```js
  import sonnerStyles from 'sonner/dist/styles.css?url';
  ```
4. Start the dev server or build your application:

   ```bash
   npm run dev
   # or
   yarn dev
   # or however you build
   ```
5. Observe the error in the console/terminal:

   ```
   Cannot find module 'sonner/dist/styles.css?url'
   ```

**Expected Behavior**

* The CSS file should still be available at the same path (`sonner/dist/styles.css`) so that importing it using the `?url` suffix works as before.
* After upgrading, no import-related errors should occur, and the toast component should continue rendering with the correct default styling.

**Actual Behavior**

* The import of `sonner/dist/styles.css?url` fails because the file is not found in the published `dist/` directory of the 2.0.4 package.
* As a result, the application build crashes, preventing usage of the Sonner Toaster and any related styling.

**Comment by dotamir** [comment]
Same here. Even downgrading to the `v2.0.3` didn't resolve the issue.
I tried removing `node_modules` and lock, but it didn't help.

**Comment by rxliuli** [comment]
虽然是无意的，但 https://github.com/emilkowalski/sonner/pull/647 also fixed this issue.

**Comment by emilkowalski** [comment]
I just released `v2.0.5` which should fix the issue, please let me know if it worked.

**Comment by rxliuli** [comment]
> Is there a way to prevent the library from injecting the CSS dynamically, so we can handle it manually—ideally by serving it as a separate file and linking to it ourselves?

Currently, the only option is to use pnpm patch to override it locally. Due to issues with shadow DOM support, I am also considering forking and releasing a new package.

**Comment by rxliuli** [comment]
> > Is there a way to prevent the library from injecting the CSS dynamically, so we can handle it manually—ideally by serving it as a separate file and linking to it ourselves?
> 
> Currently, the only option is to use pnpm patch to override it locally. Due to issues with shadow DOM support, I am also considering forking and releasing a new package.

**Comment by janhesters** [comment]
@emilkowalski 2.0.5 resolved the issue for me. Thank you! 🙏
